let data=null;const $=id=>document.getElementById(id),norm=s=>String(s??"").trim().toUpperCase();
const pick=(o,ks,d=null)=>{for(const k of ks)if(o&&o[k]!=null)return o[k];return d};const tel=()=>Array.isArray(data?.telemetria)?data.telemetria:[];
function res(x){let r=norm(pick(x,["resultado","result","estadoResultado","resultadoFinal","status"],""));return["WIN","GANADA","GANADO","WON"].includes(r)?"W":["LOSS","PERDIDA","PERDIDO","LOST"].includes(r)?"L":""}
const market=x=>String(pick(x,["mercado","market","symbol","simbolo"],"DESCONOCIDO")),dir=x=>norm(pick(x,["direccion","direction","tipoDireccion","prediction"],"")),conf=x=>Number(pick(x,["confianza","confidence","scoreConfianza","confidencePct"],0))||0,timing=x=>Number(pick(x,["timingRealMs","timingMs","desviacionTargetMs","targetDeviationMs","ajusteMs","calibracionMs","timing","timingOffsetMs"],0))||0,mode=x=>norm(pick(x,["modoEjecucion","executionMode","modo"],""));
function cls(x){let v=pick(x,["clasificacionPatron","patternClassification","clasificacion","classification","memoryClassification","historicalClassification","decisionHistorica","patternClass"],null);if(v)return norm(v);let p=pick(x,["patron","pattern","patternInfo","memoriaPatron","memoryPattern"],null);if(p&&typeof p==="object"){v=pick(p,["clasificacion","classification","clase","status"],null);if(v)return norm(v)}return"SIN DATO"}
const ts=x=>{let v=pick(x,["timestamp","ts","fechaHora","createdAt","time","hora"],null);if(v==null)return null;let n=typeof v==="number"?v:Date.parse(v);return Number.isFinite(n)?n:null};
const buck=(v,n)=>Math.round(v/n)*n,cbuck=(v,n)=>Math.floor(Math.max(0,Math.min(100,v))/n)*n,pct=(w,n)=>n?100*w/n:0;
function stat(a){let w=a.filter(x=>res(x)==="W").length;return{n:a.length,w,l:a.length-w,p:pct(w,a.length)}}
function populate(){let ms=[...new Set(tel().map(market))].sort();$("market").innerHTML='<option value="">Todos</option>'+ms.map(m=>`<option>${m}</option>`).join("")}
$("file").onchange=async e=>{let f=e.target.files[0];if(!f)return;try{data=JSON.parse(await f.text());$("fileState").textContent=`${f.name} · ${tel().length} registros`;$("summary").textContent=`TESTLOG cargado · ${tel().length} registros.`;populate()}catch(z){alert("No se pudo leer: "+z.message)}};
$("clear").onclick=()=>{data=null;$("file").value="";$("fileState").textContent="SIN ARCHIVO";$("results").classList.add("hidden")};
function sameRule(x,r,tb,cb){return market(x)===r.market&&dir(x)===r.dir&&buck(timing(x),tb)===r.t&&cbuck(conf(x),cb)===r.c&&cls(x)===r.cl}
function groups(rows,tb,cb){let m=new Map();for(const x of rows){let rr=res(x);if(!rr)continue;let r={market:market(x),dir:dir(x),t:buck(timing(x),tb),c:cbuck(conf(x),cb),cl:cls(x)};let k=[r.market,r.dir,r.t,r.c,r.cl].join("|");if(!m.has(k))m.set(k,{...r,n:0,w:0,l:0});let g=m.get(k);g.n++;rr==="W"?g.w++:g.l++}return[...m.values()]}
function ruleRows(rows,r,tb,cb){return rows.filter(x=>sameRule(x,r,tb,cb)&&res(x))}
function renderValidated(v,i,cb){return `<div class="rule good"><div class="title">#${i+1} ${v.r.market} · ${v.r.dir}</div><div class="tags"><span class="tag">${v.r.t>=0?"+":""}${v.r.t} ms</span><span class="tag">Conf. ${v.r.c}–${Math.min(100,v.r.c+cb-1)}%</span><span class="tag">${v.r.cl}</span></div><div class="metrics"><div class="metric"><small>TRAIN</small><b>${v.tr.w}/${v.tr.n} · ${v.tr.p.toFixed(1)}%</b></div><div class="metric"><small>TEST</small><b>${v.te.w}/${v.te.n} · ${v.te.p.toFixed(1)}%</b></div><div class="metric"><small>Diferencia</small><b>${(v.te.p-v.tr.p)>=0?"+":""}${(v.te.p-v.tr.p).toFixed(1)} pts</b></div><div class="metric"><small>TEST ops</small><b>${v.te.n}</b></div></div></div>`}
function walkRule(rows,r,tb,cb,nBlocks){let rr=ruleRows(rows,r,tb,cb),out=[];for(let i=0;i<nBlocks;i++){let a=Math.floor(rr.length*i/nBlocks),b=Math.floor(rr.length*(i+1)/nBlocks),s=stat(rr.slice(a,b));out.push(s)}return out}
$("run").onclick=()=>{if(!data)return alert("Primero cargue el TESTLOG.");let M=$("market").value,D=$("direction").value,tp=(+$("trainPct").value||70)/100,minTr=+$("minTrain").value||30,minTe=+$("minTest").value||15,tb=+$("bucket").value||100,cb=+$("confBucket").value||10,nBlocks=+$("blocks").value||4,maxDrop=+$("maxDrop").value||8;
let rows=tel().filter(x=>{let r=res(x);if($("finalOnly").checked&&!r)return false;if($("autoOnly").checked&&!["AUTOMATICO","AUTOMÁTICO"].includes(mode(x)))return false;if(M&&market(x)!==M)return false;if(D&&dir(x)!==D)return false;return !!r});
rows=[...rows].sort((a,b)=>{let x=ts(a),y=ts(b);return x!=null&&y!=null?x-y:0});let cut=Math.floor(rows.length*tp),train=rows.slice(0,cut),test=rows.slice(cut);
let cand=groups(train,tb,cb).filter(g=>g.n>=minTr).sort((a,b)=>pct(b.w,b.n)-pct(a.w,a.n)||b.n-a.n);
let val=[];for(const r of cand){let tr={n:r.n,w:r.w,l:r.l,p:pct(r.w,r.n)},te=stat(ruleRows(test,r,tb,cb)),drop=tr.p-te.p;if(te.n>=minTe&&drop<=maxDrop&&te.p>=50)val.push({r,tr,te,drop})}
val=val.slice(0,15);$("validated").innerHTML=val.length?val.map((v,i)=>renderValidated(v,i,cb)).join(""):"<p>No hubo reglas validadas con estos criterios.</p>";
let walks=[];for(const v of val){let blocks=walkRule(rows,v.r,tb,cb,nBlocks),nonEmpty=blocks.filter(b=>b.n>0),avg=nonEmpty.length?nonEmpty.reduce((s,b)=>s+b.p,0)/nonEmpty.length:0,minp=nonEmpty.length?Math.min(...nonEmpty.map(b=>b.p)):0,maxp=nonEmpty.length?Math.max(...nonEmpty.map(b=>b.p)):0,spread=maxp-minp,coverage=nonEmpty.length/nBlocks;let score=Math.max(0,avg-spread*0.35)*coverage;walks.push({...v,blocks,avg,minp,maxp,spread,coverage,score})}
$("walk").innerHTML=walks.length?walks.map((w,i)=>`<div class="rule"><div class="title">${w.r.market} · ${w.r.dir} · ${w.r.t>=0?"+":""}${w.r.t} ms · Conf. ${w.r.c}–${Math.min(100,w.r.c+cb-1)}%</div>${w.blocks.map((b,j)=>`<div class="block"><b>Bloque ${j+1}</b> · ${b.w}/${b.n} · ${b.p.toFixed(1)}%<div class="bar"><div class="fill" style="width:${Math.min(100,b.p)}%"></div></div></div>`).join("")}<div class="metrics"><div class="metric"><small>Promedio bloques</small><b>${w.avg.toFixed(1)}%</b></div><div class="metric"><small>Mínimo</small><b>${w.minp.toFixed(1)}%</b></div><div class="metric"><small>Variación</small><b>${w.spread.toFixed(1)} pts</b></div><div class="metric"><small>Cobertura</small><b>${Math.round(w.coverage*100)}%</b></div></div></div>`).join(""):"<p>No hay reglas para walk-forward.</p>";
walks.sort((a,b)=>b.score-a.score);$("ranking").innerHTML=walks.length?walks.map((w,i)=>`<div class="rule"><div class="rank">#${i+1}</div><div class="title">${w.r.market} · ${w.r.dir} · ${w.r.t>=0?"+":""}${w.r.t} ms · Conf. ${w.r.c}–${Math.min(100,w.r.c+cb-1)}%</div><div class="metrics"><div class="metric"><small>Score estabilidad</small><b>${w.score.toFixed(1)}</b></div><div class="metric"><small>TEST</small><b>${w.te.p.toFixed(1)}%</b></div><div class="metric"><small>Prom. bloques</small><b>${w.avg.toFixed(1)}%</b></div><div class="metric"><small>Variación</small><b>${w.spread.toFixed(1)} pts</b></div></div></div>`).join(""):"<p>Sin ranking.</p>";
$("summary").innerHTML=`Analizadas <b>${rows.length}</b> operaciones · TRAIN <b>${train.length}</b> · TEST <b>${test.length}</b> · Reglas validadas <b>${val.length}</b>.`;$("results").classList.remove("hidden");$("summary").scrollIntoView({behavior:"smooth"})};