let DATA=null;
const $=x=>document.getElementById(x),N=x=>String(x??"").trim().toUpperCase();
const get=(o,ks,d=null)=>{for(const k of ks)if(o&&o[k]!=null)return o[k];return d};
const rows=()=>Array.isArray(DATA?.telemetria)?DATA.telemetria:[];
const result=x=>{let r=N(get(x,["resultado","result","estadoResultado","resultadoFinal","status"],""));return["WIN","GANADA","GANADO","WON"].includes(r)?"W":["LOSS","PERDIDA","PERDIDO","LOST"].includes(r)?"L":""};
const market=x=>String(get(x,["mercado","market","symbol","simbolo"],"DESCONOCIDO"));
const direction=x=>N(get(x,["direccion","direction","tipoDireccion","prediction"],""));
const confidence=x=>Number(get(x,["confianza","confidence","scoreConfianza","confidencePct"],0))||0;
const timing=x=>Number(get(x,["timingRealMs","timingMs","desviacionTargetMs","targetDeviationMs","ajusteMs","calibracionMs","timing","timingOffsetMs"],0))||0;
const time=x=>{let v=get(x,["timestamp","ts","fechaHora","createdAt","time","hora"],null),n=typeof v==="number"?v:Date.parse(v);return Number.isFinite(n)?n:null};
const buck=(v,n)=>Math.round(v/n)*n,cbuck=(v,n)=>Math.floor(Math.max(0,Math.min(100,v))/n)*n,pct=(w,n)=>n?100*w/n:0;
function stat(a){let w=a.filter(x=>result(x)==="W").length;return{n:a.length,w,l:a.length-w,p:pct(w,a.length)}}

const BLOCK_PATTERNS=[/profit/i,/ganancia/i,/beneficio/i,/pnl/i,/resultado/i,/result/i,/outcome/i,/won/i,/lost/i,/win/i,/loss/i,/payout/i,/retorno/i,/return/i,/sell/i,/venta/i,/exit/i,/salida/i,/close/i,/cierre/i,/contract.*status/i,/estado.*contrato/i,/sold/i,/settlement/i,/settled/i,/final/i,/finished/i,/manualResult/i,/lastResult/i,/balanceAfter/i,/durationReal/i,/buy/i,/purchase/i,/compr/i,/confirm/i,/execution/i,/ejecucion/i,/executed/i,/manualClick/i,/clickToBuy/i,/buyLatency/i,/transaction/i,/contractId/i,/proposalId/i,/entryEpoch/i,/entryTime/i,/buyEpoch/i,/buyTime/i,/buyConfirmed/i];
const BASE_SKIP=new Set(["resultado","result","estadoResultado","resultadoFinal","status","mercado","market","symbol","simbolo","direccion","direction","tipoDireccion","prediction","confianza","confidence","scoreConfianza","confidencePct","timestamp","ts","fechaHora","createdAt","time","hora","timingRealMs","timingMs","desviacionTargetMs","targetDeviationMs","ajusteMs","calibracionMs","timing","timingOffsetMs"]);
function isBlockedPath(path){let simple=path.split(".").pop();if(BASE_SKIP.has(simple))return true;return BLOCK_PATTERNS.some(rx=>rx.test(path))}
function primitiveFeatures(x,audit=null){let out={};function scan(o,p="",d=0){if(!o||typeof o!=="object"||d>2)return;for(const[k,v]of Object.entries(o)){let key=p?p+"."+k:k;if(isBlockedPath(key)){if(audit)audit.blocked.add(key);continue}if(v==null)continue;if(typeof v==="string"||typeof v==="boolean"){let s=String(v);if(s.length<=40){out[key]=N(s);if(audit)audit.allowed.add(key)}}else if(typeof v==="number"&&Number.isFinite(v)){out[key]=v;if(audit)audit.allowed.add(key)}else if(typeof v==="object"&&!Array.isArray(v))scan(v,key,d+1)}}scan(x);return out}
function candidates(train,minN,audit){let maps=new Map();for(const x of train){let f=primitiveFeatures(x,audit);for(const[k,v]of Object.entries(f)){let val;if(typeof v==="number"){let step=Math.abs(v)<=1?.1:Math.abs(v)<=10?1:Math.abs(v)<=100?10:100;val="≈"+Math.round(v/step)*step}else val=v;let id=k+"="+val;if(!maps.has(id))maps.set(id,{key:k,val,train:[]});maps.get(id).train.push(x)}}return[...maps.values()].filter(c=>c.train.length>=minN&&c.train.length<train.length*.95).map(c=>({...c,s:stat(c.train)})).sort((a,b)=>b.s.p-a.s.p||b.s.n-a.s.n).slice(0,120)}
function matchFeature(x,c){let f=primitiveFeatures(x),v=f[c.key];if(v==null)return false;if(typeof v==="number"&&String(c.val).startsWith("≈")){let target=Number(String(c.val).slice(1)),step=Math.abs(v)<=1?.1:Math.abs(v)<=10?1:Math.abs(v)<=100?10:100;return Math.round(v/step)*step===target}return v===c.val}
function baseGroups(a,tb,cb){let m=new Map();for(const x of a){if(!result(x))continue;let r={m:market(x),d:direction(x),t:buck(timing(x),tb),c:cbuck(confidence(x),cb)},k=[r.m,r.d,r.t,r.c].join("|");if(!m.has(k))m.set(k,{...r,a:[]});m.get(k).a.push(x)}return[...m.values()]}
function baseMatch(x,r,tb,cb){return market(x)===r.m&&direction(x)===r.d&&buck(timing(x),tb)===r.t&&cbuck(confidence(x),cb)===r.c}
function walkStats(all,c,B){let wa=all.filter(x=>matchFeature(x,c)),blocks=[];for(let i=0;i<B;i++){let a=Math.floor(wa.length*i/B),b=Math.floor(wa.length*(i+1)/B);blocks.push(stat(wa.slice(a,b)))}let non=blocks.filter(x=>x.n),total=stat(wa),min=non.length?Math.min(...non.map(x=>x.p)):0,max=non.length?Math.max(...non.map(x=>x.p)):0;return{wa,blocks,total,min,max,spread:max-min,coverage:non.length/B}}
function coverage(base,sub){return base.length?100*sub.length/base.length:0}
function keyOf(x){let t=time(x);return t!=null?String(t):JSON.stringify(x).slice(0,160)}
$("file").onchange=async e=>{let f=e.target.files[0];if(!f)return;try{DATA=JSON.parse(await f.text());$("fileState").textContent=f.name+" · "+rows().length+" registros";let ms=[...new Set(rows().map(market))].sort();$("market").innerHTML='<option value="">Todos</option>'+ms.map(x=>`<option>${x}</option>`).join("");$("summary").textContent="TESTLOG cargado correctamente."}catch(e){alert("No se pudo leer el JSON: "+e.message)}};
$("clear").onclick=()=>{DATA=null;$("file").value="";$("results").classList.add("hidden");$("fileState").textContent="SIN ARCHIVO"};
$("run").onclick=()=>{if(!DATA)return alert("Primero cargue el TESTLOG.");
 let M=$("market").value,D=$("direction").value,tp=(+$("trainPct").value||70)/100,minTr=+$("minTrain").value||30,minTe=+$("minTest").value||15,minST=+$("minSubTrain").value||18,minSE=+$("minSubTest").value||12,minTestAcc=+$("minTestAcc").value||58,minWorst=+$("minWorstBlock").value||50,maxSpread=+$("maxSpread").value||20,maxRed=+$("maxRedundancy").value||90,minLossAvoided=+$("minLossAvoided").value||3,tb=+$("bucket").value||100,cb=+$("confBucket").value||10,B=+$("blocks").value||4;
 let all=rows().filter(x=>result(x)&&(!M||market(x)===M)&&(!D||direction(x)===D)),hasTime=all.length>0&&all.every(x=>time(x)!=null);if(hasTime)all=[...all].sort((a,b)=>time(a)-time(b));
 let cut=Math.floor(all.length*tp),tr=all.slice(0,cut),te=all.slice(cut);
 let bases=baseGroups(tr,tb,cb).filter(g=>g.a.length>=minTr).map(g=>({g,s:stat(g.a),test:stat(te.filter(x=>baseMatch(x,g,tb,cb)))})).filter(z=>z.test.n>=minTe&&z.test.p>=50&&z.s.p-z.test.p<=8).sort((a,b)=>b.test.p-a.test.p||b.test.n-a.test.n);
 if(!bases.length){$("base").innerHTML="<p>No hubo regla base validada.</p>";$("decision").innerHTML="<div class='status no'>SIN REGLA</div>";$("results").classList.remove("hidden");return}
 let base=bases[0],g=base.g,baseAll=all.filter(x=>baseMatch(x,g,tb,cb)),baseTr=tr.filter(x=>baseMatch(x,g,tb,cb)),baseTe=te.filter(x=>baseMatch(x,g,tb,cb)),baseTeS=stat(baseTe);
 $("base").innerHTML=`<div class="rule good"><div class="title">${g.m} · ${g.d} · ${g.t>=0?"+":""}${g.t} ms · Conf. ${g.c}–${Math.min(100,g.c+cb-1)}%</div><div class="metrics"><div class="metric"><small>TRAIN</small><b>${base.s.w}/${base.s.n} · ${base.s.p.toFixed(1)}%</b></div><div class="metric"><small>TEST</small><b>${base.test.w}/${base.test.n} · ${base.test.p.toFixed(1)}%</b></div><div class="metric"><small>Total base</small><b>${stat(baseAll).w}/${baseAll.length} · ${stat(baseAll).p.toFixed(1)}%</b></div></div></div>`;
 let audit={blocked:new Set(),allowed:new Set()},cs=candidates(baseTr,minST,audit);
 $("audit").innerHTML=`<div class="notice"><b>Bloqueados:</b> ${audit.blocked.size} · <b>Permitidos:</b> ${audit.allowed.size}</div>`;
 let evals=[];
 for(const c of cs){let subTe=baseTe.filter(x=>matchFeature(x,c)),se=stat(subTe);if(se.n<minSE)continue;let wf=walkStats(baseAll,c,B),removed=baseTe.filter(x=>!matchFeature(x,c)),remS=stat(removed),lossAvoided=removed.filter(x=>result(x)==="L").length,winsSacrificed=removed.filter(x=>result(x)==="W").length,net=lossAvoided-winsSacrificed,cover=coverage(baseTe,subTe),redundancy=cover,gain=se.p-baseTeS.p,pass=se.p>=minTestAcc&&wf.min>=minWorst&&wf.spread<=maxSpread&&wf.coverage===1&&redundancy<=maxRed&&lossAvoided>=minLossAvoided&&gain>=0;
   let score=gain*2+net*1.5+wf.min*.3-wf.spread*.25+(100-redundancy)*.08;
   evals.push({...c,se,wf,removed:remS,lossAvoided,winsSacrificed,net,cover,redundancy,gain,pass,score})
 }
 evals.sort((a,b)=>Number(b.pass)-Number(a.pass)||b.score-a.score||b.se.n-a.se.n);let top=evals.slice(0,10);
 $("incremental").innerHTML=top.length?top.map((c,i)=>`<div class="rule ${c.pass?"good":"warnRule"}"><div class="title">#${i+1} ${c.key} = ${c.val}</div><div class="metrics"><div class="metric"><small>Base TEST</small><b>${baseTeS.w}/${baseTeS.n} · ${baseTeS.p.toFixed(1)}%</b></div><div class="metric"><small>Base + filtro</small><b>${c.se.w}/${c.se.n} · ${c.se.p.toFixed(1)}%</b></div><div class="metric"><small>Mejora</small><b>${c.gain>=0?"+":""}${c.gain.toFixed(1)} pts</b></div><div class="metric"><small>Cobertura</small><b>${c.cover.toFixed(1)}%</b></div><div class="metric"><small>Pérdidas evitadas</small><b>${c.lossAvoided}</b></div><div class="metric"><small>Ganancias sacrificadas</small><b>${c.winsSacrificed}</b></div><div class="metric"><small>Neto evitado</small><b>${c.net>=0?"+":""}${c.net}</b></div><div class="metric"><small>Peor bloque</small><b>${c.wf.min.toFixed(1)}%</b></div></div></div>`).join(""):"<p>Sin candidatos con muestra suficiente.</p>";
 $("redundancy").innerHTML=top.length?top.map((c,i)=>`<div class="rule"><div class="title">${c.key} = ${c.val}</div><div class="metrics"><div class="metric"><small>Redundancia</small><b>${c.redundancy.toFixed(1)}%</b></div><div class="metric"><small>Operaciones conservadas</small><b>${c.se.n}/${baseTeS.n}</b></div><div class="metric"><small>Operaciones eliminadas</small><b>${baseTeS.n-c.se.n}</b></div><div class="metric"><small>Clasificación</small><b>${c.redundancy>=90?"MUY REDUNDANTE":c.redundancy>=75?"REDUNDANTE":"APORTA FILTRO"}</b></div></div></div>`).join(""):"<p>Sin datos.</p>";
 let best=top.find(x=>x.pass)||top[0];
 if(best){$("walk").innerHTML=`<div class="rule ${best.pass?"good":"warnRule"}"><div class="title">${best.key} = ${best.val}</div>${best.wf.blocks.map((s,i)=>`<div class="block"><b>Bloque ${i+1}</b> · ${s.n?`${s.w}/${s.n} · ${s.p.toFixed(1)}%`:"SIN MUESTRA"}<div class="bar"><div class="fill" style="width:${s.p}%"></div></div></div>`).join("")}<div class="metrics"><div class="metric"><small>Total</small><b>${best.wf.total.w}/${best.wf.total.n} · ${best.wf.total.p.toFixed(1)}%</b></div><div class="metric"><small>Peor bloque</small><b>${best.wf.min.toFixed(1)}%</b></div><div class="metric"><small>Variación</small><b>${best.wf.spread.toFixed(1)} pts</b></div><div class="metric"><small>Redundancia</small><b>${best.redundancy.toFixed(1)}%</b></div></div></div>`}else $("walk").innerHTML="<p>Sin candidato.</p>";
 let passed=top.filter(x=>x.pass);
 if(passed.length){$("decision").innerHTML=`<div class="status ok">APORTA VALOR INCREMENTAL</div><p>${passed[0].key} = ${passed[0].val} mejora el TEST, evita pérdidas netas y no es excesivamente redundante.</p>`}
 else if(top.length){$("decision").innerHTML=`<div class="status mid">NO JUSTIFICA AÑADIR FILTRO</div><p>Hay condiciones estables, pero todavía no demuestran suficiente valor adicional sobre la regla base.</p>`}
 else $("decision").innerHTML=`<div class="status no">SIN CANDIDATO</div>`;
 $("diag").innerHTML=`<div class="notice"><b>Orden:</b> ${hasTime?"timestamp detectado":"orden original del TESTLOG"}.<br><b>Base TEST:</b> ${baseTeS.n} operaciones.<br><b>Candidatos pre-entry:</b> ${cs.length}.<br><b>Evaluados con TEST suficiente:</b> ${evals.length}.<br><b>Con valor incremental:</b> ${passed.length}.<br><br>La V3.5 penaliza filtros que solo repiten la regla base y muestra explícitamente pérdidas evitadas vs ganancias sacrificadas.</div>`;
 $("summary").innerHTML=`Analizadas <b>${all.length}</b> · TRAIN <b>${tr.length}</b> · TEST <b>${te.length}</b> · candidatos con valor incremental <b>${passed.length}</b>.`;
 $("results").classList.remove("hidden");$("summary").scrollIntoView({behavior:"smooth"})
};